name: code

on: 
  pull_request_target:
      types: [opened, synchronize, edited]

jobs:
  code:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
        with:
          path: projects

      - name: install flake8
        run: |
          pip install flake8
          pip install black

      - name: checkout
        run: |
          cd projects

          base_ref=${{ github.base_ref }}
          pr_number=${{ github.event.pull_request.number }}
          head_sha=${{ github.event.pull_request.head.sha }}
          base_sha=${{ github.event.pull_request.base.sha  }}
          
          git fetch origin $base_ref:base_ref
          git fetch origin pull/$pr_number/head:pr_ref
          git checkout $head_sha
          git diff $base_sha $head_sha --diff-filter=ACMR --name-only > ${{ github.workspace }}/git_diff.txt
          cat ${{ github.workspace }}/git_diff.txt | grep '/' | cut -d'/' -f1 | sort | uniq |  sed -e '/deprecated/d' -e '/.github/d' > ${{ github.workspace }}/changed_projects_folder.txt

          echo =================
          cat ${{ github.workspace }}/changed_projects_folder.txt

      - name: auto fix
        run: |
          cd projects
          while IFS= read -r line; do
            echo ==========================================
            echo "Fixing code convention for: $line"
            black $line
          done < ${{ github.workspace }}/changed_projects_folder.txt

      - name: Upload Result
        uses: actions/upload-artifact@v4
        with:
          name: auto_fixed
          path: projects
          
      - name: run flake8
        run: |
          cd projects
          while IFS= read -r line; do
            echo ==========================================
            echo "Checking code convention for: $line"
            flake8 $line
          done < ${{ github.workspace }}/changed_projects_folder.txt
          
