name: code

on: 
  push:

jobs:
  code:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: run flake8
        run: |
          pip install flake8

          flake8 .
